config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :services, only: [:index]
  resources :packages, only: %i[index show]
  resources :tests, only: [:index]
  resources :dermoesthetics, only: [:index]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dermoesthetic.rb
class Dermoesthetic < ApplicationRecord
  belongs_to :user
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :user
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tests
  has_many :services
  has_many :dermoesthetics
  has_many :packages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dermoesthetics_controller.rb
class DermoestheticsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    @dermoesthetics = Dermoesthetic.all
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_package, only: %i[show]
  def index
    @packages = Package.all
  end

  def show
  end
end

private

def find_package
  @package = Package.find(params[:id])
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @tests = Test.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dermoesthetics/index.html.erb
<div class="wrapping-div">
  <div class="container analiza-container mb-0">
    <div class="row">
      <div class="col-12 col-lg-6">
      </div>
    </div>
    <% @dermoesthetics.each do |dermoesthetic| %>
      <div class="service-card">
        <div class="service-name">
          <strong>
            <%= p dermoesthetic.name %>
          </strong>
        </div>
        <div class="separate">
          <p> </p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container analiza-container mt-3">
    <%= link_to "<-- Mbrapa", root_path, class: "home-links analiza-link mt-0 mx-0" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google result tags-->
    <title>PiperoCare | Albania's Best Healthcare Clinic</title>
    <meta name="description" content="Medical Center Dr. Pipero, ofron sherbime mjekësore bashkëkohore. Konsulta në sëmundje të ndryshme, analiza mjekësore dhe shërbime të dermokozmetikës">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- end Google result tags-->

    <!-- Favicon links-->
    <%= favicon_link_tag "pipero_logo.png", rel: "icon", type: "image/png", style: "width: 32px; height: 32px;" %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <!-- end Favicon links-->

    <!-- Facebook tags -->
    <meta property="og:title" content="PiperoCare | Albania's Best Healthcare Clinic">
    <meta property="og:image" content="klinika_pipero.jpeg">
    <meta property="og:description" content="Medical Center Dr. Pipero, ofron sherbime mjekësore bashkëkohore. Konsulta në sëmundje të ndryshme, analiza mjekësore dhe shërbime të dermokozmetikës">
    <meta property="og:site_name" content="PiperoCare"/>
    <!-- end Facebook tags -->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia&effect=fire">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= image_tag "banner.png" , id: "home-banner"%>

<div class="container d-flex justify-content-center align-items-center home-links-container">
  <div class="row">
    <div class="col-12 col-lg-12 home-links-div">
      <%= link_to "Paketat", packages_path, class: "home-links" %>
      <%= link_to "Shërbime", services_path, class: "home-links" %>
      <%= link_to "Analiza", tests_path, class: "home-links" %>
      <%= link_to "Dermo-Estetike", dermoesthetics_path, class: "home-links" %>
    </div>
  </div>
</div>


<div class="info-container mb-3 pb-5">
  <div class="info-contact">
    <h5>Kontaktoni:</h5>
    <div class="d-flex">
      <div class="d-flex w-50">
        <i class="fa-solid fa-phone"></i> <p>+355 69 70 48 000</p>
      </div>
      <div class="d-flex w-50">
        <i class="fa-solid fa-envelope"></i> <p>info@piperocare.com</p>
      </div>
    </div>
  </div>
  <div class="info-address w-100">
    <h5>Addresa:</h5>
    <div class="d-flex justify-content-between">
      <%= link_to "https://www.google.com/maps/place/Medical+Center+Dr.Pipero/@41.2828935,19.8604931,17z/data=!3m1!4b1!4m6!3m5!1s0x135037400021b355:0x165494d89bef80f2!8m2!3d41.2828935!4d19.863068!16s%2Fg%2F11f0kxkb3k?entry=ttu", class: "navbar-brand w-50" do %>
        <div class="d-flex">
          <i class="fa-solid fa-location-dot"></i>
          <h6>Lunder</h6>
        </div>
        <p>Kompleksi Colombo 2, <br>Rruga Vilave,TEG</p>
      <% end %>

      <%= link_to "https://www.google.com/maps/place/PiperoCare+Astir/@41.328349,19.7828053,17z/data=!3m1!4b1!4m6!3m5!1s0x1350317ea4a58201:0xce3994d3e5ec48ff!8m2!3d41.328349!4d19.7853802!16s%2Fg%2F11rznryd49?entry=ttu", class: "navbar-brand w-50" do %>
        <div class="d-flex w-50">
          <i class="fa-solid fa-location-dot"></i>
          <h6>Tiranë</h6>
        </div>
        <p>Rruga Teodor Keko, <br>Pallati Ales, Kati I, Tiranë</p>
      <% end %>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="container service-container">
  <% @services.each do |service| %>
    <div class="service-card">
      <div class="service-name">
        <strong>
          <%= p service.name %>
        </strong>
      </div>
      <div class="separate">
      <p> </p>
      </div>
      <div class="service-info">
        <strong class="price">
          <%= p service.price %>
        </strong>
        <p class="currency">
          <%= p service.currency %>
        </p>
      </div>
    </div>
  <% end %>
  <br>
  <%= link_to "<-- Mbrapa", root_path, class: "home-links mt-2 py-3" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <%= notice %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <%= alert %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="contact">
    <div class="d-flex">
      <h6 class="me-1">Kontaktoni:</h6>
      <div>
        <div class="d-flex">
          <i class="fa-solid fa-phone me-1"></i> <p>+355 69 70 48 000</p>
        </div>
        <div class="d-flex">
          <i class="fa-solid fa-envelope me-1"></i> <p>info@piperocare.com</p>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper">
    <h6>Follow Us</h6>
    <div class="footer-links-div">
      <a href="https://www.instagram.com/piperocare/?hl=en" class="footer-links"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/piperocare/" class="footer-links"><i class="fab fa-facebook"></i></a>
    </div>
  </div>
  <div class="address">
    <div class="d-flex justify-content-end">
      <h6 class="me-1">Adresa:</h6>
      <div>
        <%= link_to "https://www.google.com/maps/place/Medical+Center+Dr.Pipero/@41.2828935,19.8604931,17z/data=!3m1!4b1!4m6!3m5!1s0x135037400021b355:0x165494d89bef80f2!8m2!3d41.2828935!4d19.863068!16s%2Fg%2F11f0kxkb3k?entry=ttu", class: "navbar-brand" do %>
          <div class="d-flex">
            <i class="fa-solid fa-location-dot me-1"></i>
            <h6>Lunder</h6>
          </div>
        <% end %>
        <%= link_to "https://www.google.com/maps/place/PiperoCare+Astir/@41.328349,19.7828053,17z/data=!3m1!4b1!4m6!3m5!1s0x1350317ea4a58201:0xce3994d3e5ec48ff!8m2!3d41.328349!4d19.7853802!16s%2Fg%2F11rznryd49?entry=ttu", class: "navbar-brand" do %>
          <div class="d-flex">
            <i class="fa-solid fa-location-dot me-1"></i>
            <h6>Tiranë</h6>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "pipero_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item active">
              <%= link_to "Admin",rails_admin_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Admin", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>